-- Multi-toko, fase 3: catatan aktivitas admin (siapa melakukan apa, di toko mana).
-- Hanya menambah tabel baru.

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- NULL = aktivitas tingkat platform.
  store_id TEXT REFERENCES stores (id) ON DELETE SET NULL,
  -- Sengaja tanpa foreign key: catatan tetap ada walau akun admin dihapus.
  user_id TEXT,
  user_email TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL,
  target_type TEXT NOT NULL DEFAULT '',
  target_id TEXT NOT NULL DEFAULT '',
  meta_json TEXT NOT NULL DEFAULT '{}',
  ip TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_store_created ON audit_logs (store_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs (user_id);
