import { NextResponse } from 'next/server';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { getD1, getFiles } from '@/db';
const schemaSql=`CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, tone TEXT NOT NULL, price INTEGER NOT NULL, stock INTEGER NOT NULL DEFAULT 0, image_url TEXT, image_key TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`;
async function auth(){const u=await getChatGPTUser();if(!u)return false;return Boolean(await getD1().prepare('SELECT user_id FROM admin_users WHERE user_id=?').bind(u.userId).first())}
async function saveImage(file:File|null){if(!file||!file.size)return null;if(file.size>5_000_000||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Foto harus JPG, PNG, atau WebP maksimal 5 MB.');const ext=file.type.split('/')[1].replace('jpeg','jpg');const key=`products/${crypto.randomUUID()}.${ext}`;await getFiles().put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});return key}
export async function GET(){if(!await auth())return NextResponse.json({error:'Tidak diizinkan.'},{status:403});const d1=getD1();await d1.prepare(schemaSql).run();const r=await d1.prepare("SELECT id,name,category,tone,price,stock,active,COALESCE('/api/product-image/' || image_key,image_url) AS image FROM products ORDER BY updated_at DESC").all();return NextResponse.json({products:r.results})}
export async function POST(req:Request){if(!await auth())return NextResponse.json({error:'Tidak diizinkan.'},{status:403});try{const f=await req.formData();const name=String(f.get('name')||'').trim(),category=String(f.get('category')||'').trim(),tone=String(f.get('tone')||'').trim();const price=Number(f.get('price')),stock=Number(f.get('stock'));if(!name||!category||!tone||price<=0||stock<0)throw new Error('Lengkapi data produk.');const imageKey=await saveImage(f.get('image') as File|null);if(!imageKey)throw new Error('Pilih foto produk.');const id=crypto.randomUUID(),now=new Date().toISOString(),d1=getD1();await d1.prepare(schemaSql).run();await d1.prepare('INSERT INTO products (id,name,category,tone,price,stock,image_key,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,name,category,tone,price,stock,imageKey,1,now,now).run();return NextResponse.json({ok:true,id})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Gagal menyimpan.'},{status:400})}}
export async function PATCH(req:Request){if(!await auth())return NextResponse.json({error:'Tidak diizinkan.'},{status:403});try{const f=await req.formData();const id=String(f.get('id')||''),name=String(f.get('name')||'').trim(),category=String(f.get('category')||'').trim(),tone=String(f.get('tone')||'').trim();const price=Number(f.get('price')),stock=Number(f.get('stock')),active=String(f.get('active'))==='true'?1:0;const d1=getD1(),old=await d1.prepare('SELECT image_key FROM products WHERE id=?').bind(id).first<{image_key:string|null}>();const newKey=await saveImage(f.get('image') as File|null);await d1.prepare('UPDATE products SET name=?,category=?,tone=?,price=?,stock=?,active=?,image_key=COALESCE(?,image_key),updated_at=? WHERE id=?').bind(name,category,tone,price,stock,active,newKey,new Date().toISOString(),id).run();if(newKey&&old?.image_key)await getFiles().delete(old.image_key);return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Gagal memperbarui.'},{status:400})}}
export async function DELETE(req:Request){if(!await auth())return NextResponse.json({error:'Tidak diizinkan.'},{status:403});const {id}=await req.json() as {id:string};const d1=getD1(),row=await d1.prepare('SELECT image_key FROM products WHERE id=?').bind(id).first<{image_key:string|null}>();await d1.prepare('DELETE FROM products WHERE id=?').bind(id).run();if(row?.image_key)await getFiles().delete(row.image_key);return NextResponse.json({ok:true})}
